# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='named_entity_label',
            field=models.CharField(blank=True, choices=[('PERSON', 'People, including fictional'), ('FACILITY', 'Buildings, airports, highways, bridges, etc.'), ('ORG', 'Companies, agencies, institutions, etc.'), ('GPE', 'Countries, cities, states'), ('LOC', 'Non-GPE locations, mountain ranges, bodies of water'), ('PRODUCT', 'Objects, vehicles, foods, etc. (not services)'), ('EVENT', 'Named hurricanes, battles, wars, sports events, etc.'), ('WORK_OF_ART', 'Titles of books, songs, etc.'), ('LANGUAGE', 'Any named language'), ('DATE', 'Absolute or relative dates or periods'), ('TIME', 'Times smaller than a day'), ('MONEY', 'Monetary values, including unit'), ('QUANTITY', 'Measurements, as of weight or distance'), ('ORDINAL', '"first", "second", etc.')], default='', max_length=16),
        ),
    ]
