# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20171126_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='descritpion',
            new_name='description',
        ),
    ]
