# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_bot_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('keywords', models.TextField()),
                ('children', models.ManyToManyField(blank=True, to='bots.Node')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bots.Node'),
        ),
    ]
