# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_auto_20171126_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='node',
            new_name='start_node',
        ),
    ]
