# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_auto_20171126_2128'),
        ('messaging', '0002_auto_20171126_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='bots.Node'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='bots.Bot'),
        ),
    ]
